name: lang_mate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  geolocator: ^14.0.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.6
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/images/
    - assets/images/world_background.jpg
    - assets/icons/
    - assets/animations/

  uses-material-design: true

flutter_launcher_icons:
  adaptive_icon_foreground: "assets/icons/app_logo4_white.png"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/icons/app_logo4_white.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff" # background color
  image: assets/icons/app_logo4_rounded.png # logo
  android: true
  ios: true

  android_12:
    image: assets/icons/app_logo4_rounded.png # also for Android 12+
    color: "#ffffff" # background for Android 12
